[package]
name = "ray_tracing_in_one_weekend"
version = "0.1.0"
authors = ["Wei Liu <liuw@liuw.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
